image: node

stages:
  - build
test-unit:
  stage: build
  script: 
    - npm ci --also=dev 
    - npm run test
    - npm run build
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days
    reports:
      cobertura: coverage/cobertura-coverage.xml