image: node

stages:
  - build
build:
  stage: build
  script: 
    - npm ci --also=dev 
    - npm run test
    - npm run build
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml