image: node

stages:
  - install
  - test-unit
test-unit:
  stage: test-unit
  script: npm ci --also=dev && npm run test
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days