image: node

stages:
  - install
  - test-unit
install:
  stage: install
  script: npm ci
test-unit:
  stage: test-unit
  script: npm run test
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days