image: node
stages:
  - build
test-unit:
  stage: build
  script: 
    - npm ci --also=dev 
    - npm run test
    - npm run build
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml